dorm_detective/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dorm_detective_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
    path('dorm-detective/', include('dorm_detective_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dorm_detective_app/urls.py
from django.urls import path, include
from dorm_detective_app import views

app_name = 'dorm-detective'

urlpatterns = [
    path('', views.index, name='index'),
    path('universities/', views.universities, name='universities'),
    path('universities/<slug:university_slug>/', views.university, name='university'),
    path('universities/<slug:university_slug>/<slug:accommodation_slug>/', views.accommodation, name='accommodation'),
    path('about/', views.about, name="about"),
    path('FAQ/', views.faq, name='faq'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('account/<int:user_id>/', views.my_account, name='my_account'),
    path('add-like/', views.add_like, name="add_like"),
    path('delete-account/<int:user_id>/', views.delete_account, name="delete_account"),
    path('logout/', views.custom_logout, name='auth_logout'),
    path('', include('registration.backends.simple.urls'))
]

dorm_detective_app/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone


class University(models.Model):
    NAME_MAX_LENGTH = 128
    DESCRIPTION_MAX_LENGTH = 2048
    SYNOPSIS_MAX_LENGTH = 1024

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    latitude = models.DecimalField(
        max_digits=8,
        decimal_places=6,
        validators=[
            MaxValueValidator(90.0),
            MinValueValidator(-90.0),
        ],
        default=0,
    )
    longitude = models.DecimalField(
        max_digits=9,
        decimal_places=6,
        validators=[
            MaxValueValidator(180.0),
            MinValueValidator(-180.0),
        ],
        default=0,
    )
    description = models.CharField(max_length=DESCRIPTION_MAX_LENGTH, default="Description")
    picture = models.ImageField(upload_to='university_images', blank=True, null=True)
    website = models.URLField(blank=True)
    synopsis = models.CharField(max_length=SYNOPSIS_MAX_LENGTH, default="Synopsis")
    slug = models.SlugField(unique=True)
    email_domain = models.CharField(max_length=128, default="example.com")

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(University, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Universities'

    def __str__(self):
        return self.name



class Accommodation(models.Model):
    NAME_MAX_LENGTH = 128
    DESCRIPTION_MAX_LENGTH = 2048

    university = models.ForeignKey(University, on_delete=models.CASCADE, blank=False)
    name = models.CharField(max_length=NAME_MAX_LENGTH)
    description = models.CharField(max_length=DESCRIPTION_MAX_LENGTH, default="Description")
    latitude = models.DecimalField(
        max_digits=8,
        decimal_places=6,
        validators=[
            MaxValueValidator(90.0),
            MinValueValidator(-90.0),
        ],
        default=0,
    )
    longitude = models.DecimalField(
        max_digits=9,
        decimal_places=6,
        validators=[
            MaxValueValidator(180.0),
            MinValueValidator(-180.0),
        ],
        default=0,
    )
    rent_max = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        validators=[
            MinValueValidator(0.0),
        ],
        # default=0.0,
        null=True,
        blank=True
    )
    rent_min = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        validators=[
            MinValueValidator(0.0),
        ],
        # default=0.0,
        null=True,
        blank=True
    )
    avg_rating = models.DecimalField(
        max_digits=2,
        decimal_places=1,
        validators=[
            MaxValueValidator(5.0),
            MinValueValidator(1.0),
        ],
        null=True,
        blank=True
    )
    reviews_no = models.IntegerField(
        validators=[
            MinValueValidator(0),
        ],
        default=0
    )
    picture = models.ImageField(upload_to='accommodation_images', blank=True, null=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Accommodation, self).save(*args, **kwargs)

    class Meta:
        unique_together = ('university', 'name')

    def __str__(self):
        return self.university.__str__() + " - " + self.name


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    current_student = models.BooleanField(default=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username


class Review(models.Model):
    TITLE_MAX_LENGTH = 128
    DESCRIPTION_MAX_LENGTH = 1024

    accommodation = models.ForeignKey(Accommodation, on_delete=models.CASCADE, blank=False)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, blank=False)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    description = models.CharField(max_length=DESCRIPTION_MAX_LENGTH)
    isAnonymous = models.BooleanField(default=False)
    picture = models.ImageField(upload_to='review_images', blank=True, null=True)
    likes = models.IntegerField(
        validators=[
            MinValueValidator(0),
        ],
        default=0
    )
    rating = models.IntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ],
        default=5
    )
    datetime = models.DateTimeField(blank=False, default=timezone.now())

    def __str__(self):
        return self.accommodation.__str__() + " " + self.title + " by user " + self.user.__str__()

dorm_detective_app/forms.py
from django.contrib.auth.models import User
from .models import UserProfile, Review, University
from django import forms
from registration.forms import RegistrationForm

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('current_student',)
    
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['accommodation', 'title', 'description', 'picture', 'rating', 'isAnonymous']
        widgets = {
            'accommodation': forms.HiddenInput(),
            'title': forms.TextInput(attrs={'placeholder': 'Title', 'class': 'form-control'}),
            'description': forms.Textarea(attrs={'placeholder': 'Description', 'class': 'form-control', 'rows': 5}),
            'picture': forms.FileInput(attrs={'class': 'form-control'}),
            'rating': forms.Select(choices=[(i, i) for i in range(1, 6)], attrs={'class': 'form-control'}),
            'isAnonymous': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

        labels = {
            'title': 'Title',
            'description': 'Description',
            'picture': 'Picture (optional)',
            'rating': 'Rating (1-5)',
            'isAnonymous': 'Post as anonymous',
        }

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.fields['accommodation'].required = False
        self.fields['picture'].required = False


class CustomRegistrationForm(RegistrationForm):
    current_student = forms.BooleanField(
        required=False,
        initial=False,
        label="I am a student",
    )

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        current_student = cleaned_data.get('current_student')

        if email and current_student:
            domain = email.split('@')[1]

            allowed_domains = set()
            universities = University.objects.all()
            for university in universities:
                allowed_domains.add(university.email_domain)

            if domain not in allowed_domains:
                self.add_error('email', "Please use a student university e-mail address from an institution that our website supports.")

    def save(self, commit=True):
        user = super().save(commit=commit)
        if commit:
            default_profile_pic_url = '/static/images/default_pp.png'
            UserProfile.objects.create(user=user, current_student=self.cleaned_data['current_student'], picture=default_profile_pic_url)
        return user

dorm_detective_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from dorm_detective_app.models import *
from django.contrib.auth import logout
from dorm_detective_app.forms import ReviewForm


def index(request):
    universities = University.objects.all()
    universities_supported = universities.count()
    students_no = User.objects.all().count()

    try:
        accommodations = Accommodation.objects.all()

        accommodations_ratings = {}

        total_reviews = 0

        total_likes = 0

        for accommodation in accommodations:
            rating_score = 0
            reviews = Review.objects.filter(accommodation=accommodation)

            if reviews.count() > 0:
                total_reviews += reviews.count()

                for review in reviews:
                    rating_score += review.rating
                    total_likes += review.likes

                rating_score / reviews.count()

                accommodations_ratings[accommodation] = rating_score

        highest_rated_accommodations = sorted(accommodations_ratings, key=accommodations_ratings.get)[:4]

    except Accommodation.DoesNotExist:
        highest_rated_accommodations = None
        total_reviews = None

    context = {"universities": universities, "universities_supported": universities_supported,
               "accommodations": highest_rated_accommodations, "total_reviews": total_reviews,
               "students_no": students_no, "total_likes": total_likes}
    template_name = 'dorm_detective_app/index.html'
    return render(request, template_name, context)


def about(request):
    universities = University.objects.all()
    context = {"universities": universities}
    template_name = 'dorm_detective_app/about.html'
    return render(request, template_name, context)


def contact_us(request):
    universities = University.objects.all()
    context = {"universities": universities}
    template_name = 'dorm_detective_app/contact_us.html'
    return render(request, template_name, context)


def faq(request):
    universities = University.objects.all()
    context = {"universities": universities}
    template_name = 'dorm_detective_app/faq.html'
    return render(request, template_name, context)


@login_required
def my_account(request, user_id):
    user = User.objects.get(id=user_id)
    user_profile = UserProfile.objects.get(user=user)
    universities = University.objects.all()
    reviews = Review.objects.filter(user=user.userprofile)
    context = {"universities": universities, "reviews": reviews, "user": user, "user_profile": user_profile}
    template_name = 'dorm_detective_app/my_account.html'
    return render(request, template_name, context)


@login_required
def delete_account(request, user_id):
    logout(request)

    user = User.objects.get(id=user_id)
    user_profile = UserProfile.objects.get(user=user)

    user_profile.delete()
    user.delete()

    return redirect("/dorm-detective/")


def custom_logout(request):
    logout(request)
    return redirect('index')


def universities(request):
    universities = University.objects.all()
    accommodations = Accommodation.objects.all()
    context = {"universities": universities, "accommodations": accommodations}
    template_name = 'dorm_detective_app/universities.html'
    return render(request, template_name, context)


def university(request, university_slug):
    universities = University.objects.all()

    try:
        university = University.objects.get(slug=university_slug)
        accommodations = Accommodation.objects.filter(university=university)
    except University.DoesNotExist:
        university = None
        accommodations = None

    if university is None:
        return redirect('/dorm-detective/')

    context = {"universities": universities, "university": university, "accommodations": accommodations}
    template_name = 'dorm_detective_app/university.html'
    return render(request, template_name, context)


def accommodation(request, university_slug, accommodation_slug):
    universities = University.objects.all()

    try:
        accommodation = Accommodation.objects.get(slug=accommodation_slug)
        university = accommodation.university
        reviews = Review.objects.filter(accommodation=accommodation).order_by('-datetime')

        avg_rating = 0
        for review in reviews:
            rating = review.rating
            avg_rating += rating

        rating_no = reviews.count()
        if rating_no >= 1:
            avg_rating /= rating_no
            avg_rating = round(avg_rating, 1)

    except Accommodation.DoesNotExist:
        accommodation = None
        university = None
        avg_rating = None
        rating_no = None
    except Review.DoesNotExist:
        reviews = None
        avg_rating = None
        rating_no = None

    user_profile = None
    if request.user.is_authenticated:
        try:
            user_profile = UserProfile.objects.get(user=request.user)
        except UserProfile.DoesNotExist:
            pass

    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.accommodation = accommodation
            review.user = user_profile
            review.save()
            return redirect('.')
    else:
        form = ReviewForm()

    context = {"universities": universities, "accommodation": accommodation, "university": university,
               "reviews": reviews, "avg_rating": avg_rating, "rating_no": rating_no, "form": form,
               "user_profile": user_profile}
    template_name = 'dorm_detective_app/accommodation.html'
    return render(request, template_name, context)


def add_like(request):
    if request.method == "POST":
        pk = request.POST["pk"]

        try:
            review = Review.objects.get(pk=pk)
            review.likes += 1
            review.save()
        except Review.DoesNotExist:
            pass
    return HttpResponse()


@login_required
def logout_account(request):
    logout(request)

    return redirect("/dorm-detective/")

templates/dorm_detective_app/accommodation.html
{% extends 'dorm_detective_app/base.html' %}
{% load staticfiles %}
{% load leaflet_tags %}

{% if accommodation %}
    {% block title_block %}
        {{ accommodation.name }}
    {% endblock %}
{% endif %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'dorm-detective:index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'dorm-detective:universities' %}">Universities</a></li>
            <li class="breadcrumb-item"><a
                    href="{% if university.slug %}{% url 'dorm-detective:university' university.slug %}
                {% endif %}">{{ university.name }}</a></li>
            <li class="breadcrumb-item active">{% if accommodation.name %}{{ accommodation.name }}{% endif %}</li>
        </ol>
    </nav>

    <div class="container-fluid">
        <div class="row mb-3">
            <div class="col-lg-4">
                <div class="row mb-1">
                    <img class="w-100 h-100" src="{% if accommodation.picture %}{{ MEDIA_URL }}{{ accommodation.picture }}{% else %}{{ STATIC_URL }}images/accom_default.jpg{% endif %}" alt="accommodation picture">
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-8 shadow p-3 bg-body rounded">
                        {% if accommodation %}
                            <h6 class="text-center"><b>Average Weekly Rent:</b> £{{ accommodation.rent_min }} -
                                £{{ accommodation.rent_max }}</h6>
                            <h6 class="text-center"><b>Average Rating:</b> {{ avg_rating }} / 5.0</h6>
                            <h6 class="text-center"><b>Total Reviews:</b> {{ rating_no }}</h6>
                        {% endif %}
                    </div>
                </div>

            </div>
            <div class="col-lg-8">
                <div class="d-flex align-items-center justify-content-center mb-3">
                    <h1 class="text-primary"><b>{% if accommodation.name %}{{ accommodation.name }}{% endif %}</b></h1>
                </div>
                <div class="about-content d-flex align-items-center justify-content-center shadow p-3 bg-body rounded">
                    <p class="text-center">
                        {% if accommodation.name %}
                            {{ accommodation.description }}
                        {% else %}
                            No description yet.
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="row align-items-center justify-content-center">
                    <h2 class="text-center text-primary"><b>Location</b></h2>
                </div>
                <div class="row">
                    <div>
                        {% leaflet_map "map" %}
                    </div>
                </div>
            </div>
            <div class="col-lg-8">

                <div class="row">
                    {% if user_profile.current_student %}
                        <h2 class="text-center text-primary"><b>Leave A Review</b></h2>
                        <div class="row">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit">Submit</button>
                            </form>
                        </div>
                    {% endif %}
                </div>
                <div class="row">
                    <h2 class="text-center text-primary"><b>Reviews</b></h2>
                    <div class="card-body">
                        {% for r in reviews %}
                            <div class="card mb-3">
                                <div class="row g-0">
                                    {% if r.picture %}
                                        <div class="col-md-4">
                                            <img src="{{ MEDIA_URL }}{{ r.picture }}"
                                                 class="d-block card-img">
                                        </div>
                                    {% endif %}
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ r.title }}</h5>
                                            <p class="card-text">{{ r.description }}</p>
                                            {% if r.user %}
                                                {% if r.isAnonymous == False %}
                                                    <span class="card-text text-muted"><img class="rounded-circle"
                                                         src="{{ MEDIA_URL }}{{ r.user.picture }}" height="35px;"
                                                         width="35px;">
                                                     {{ r.user }}</span>
                                                {% else %}
                                                    <span class="card-text text-muted"><i class="fas fa-user"></i> Anonymous</span>
                                                {% endif %}
                                            {% endif %}
                                            <p class="card-text text-muted mt-3">
                                                <i class="fas fa-award"></i>
                                                {% if r.rating == 1 %}
                                                    <i class="fas fa-star text-warning"></i>
                                                    <i class="fas fa-star"></i>
                                                    <i class="fas fa-star"></i>
                                                    <i class="fas fa-star"></i>
                                                    <i class="fas fa-star"></i>
                                                {% elif r.rating == 2 %}
                                                    <i class="fas fa-star text-warning"></i>
                                                    <i class="fas fa-star text-warning"></i>
                                                    <i class="fas fa-star"></i>
                                                    <i class="fas fa-star"></i>
                                                    <i class="fas fa-star"></i>
                                                {% elif r.rating == 3 %}
                                                    <i class="fas fa-star text-warning"></i>
                                                    <i class="fas fa-star text-warning"></i>
                                                    <i class="fas fa-star text-warning"></i>
                                                    <i class="fas fa-star"></i>
                                                    <i class="fas fa-star"></i>
                                                {% elif r.rating == 4 %}
                                                    <i class="fas fa-star text-warning"></i>
                                                    <i class="fas fa-star text-warning"></i>
                                                    <i class="fas fa-star text-warning"></i>
                                                    <i class="fas fa-star text-warning"></i>
                                                    <i class="fas fa-star"></i>
                                                {% elif r.rating == 5 %}
                                                    <i class="fas fa-star text-warning"></i>
                                                    <i class="fas fa-star text-warning"></i>
                                                    <i class="fas fa-star text-warning"></i>
                                                    <i class="fas fa-star text-warning"></i>
                                                    <i class="fas fa-star text-warning"></i>
                                                {% endif %}
                                            </p>
                                            <p class="card-text text-muted"><i
                                                    class="fas fa-calendar"></i> {{ r.datetime }}</p>
                                            <p class="card-text">
                                                <i class="fas fa-thumbs-up text-muted"
                                                   onclick="addLike({{ r.pk }})"></i>
                                                <span id="like-count-{{ r.pk }}">{{ r.likes }}</span>
                                            </p>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <form id="csrf">
            {% csrf_token %}
        </form>

        <script href="{{ STATIC_URL }}/js/carousel.js" type="text/javascript"></script>
        <script>
            const osm_map = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '<a href="https://www.openstreetmap.org/copright">OpenStreetMap</a>'
            });

            const map = L.map('map', {
                layers: [osm_map]
            }).setView([{{ accommodation.latitude }}, {{ accommodation.longitude }}], 12);

            const marker = new L.Marker([{{ accommodation.latitude }}, {{ accommodation.longitude }}]);
            marker.addTo(map)
        </script>
        <script>
            function addLike(pk) {
                console.log($("#csrf").serializeArray()[0]["value"]);
                console.log(pk);
                $.ajaxSetup({
                    headers: {
                        'X-CSRFToken': $("#csrf").serializeArray()[0]["value"]
                    }
                });
                $.ajax({
                    url: "/dorm-detective/add-like/",
                    type: "POST",
                    data: {"pk": pk}
                }).done(function (response) {
                    console.log(response);
                });

                $("#like-count-" + pk.toString()).text(parseInt($("#like-count-" + pk.toString()).text()) + 1);
            }
        </script>

{% endblock %}

templates/dorm_detective_app/base.html
<!DOCTYPE html>

{% load staticfiles %}
{# {% load leaflet_tags %}#}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
{#    {% leaflet_js %}#}
{#    {% leaflet_css %}#}
    <link rel="icon" href="{% static 'images/dd_favicon.png' %}" type="image/png">
    <title>
        {% block title_block %}{% if block.content %}{{ block.content }}{% else %} Dorm Detective {% endif %}{% endblock title_block %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-primary navbar-light fixed-top">
        <div class="container-fluid">
            <ul class="navbar-nav flex-grow-1 justify-content-center nav-fill align-items-center">
                <a class="navbar-brand text-light" href="{% url 'dorm-detective:index' %}">
                    <img src="{% static 'images/dd_logo.png' %}" alt="Dorm Detective Logo" height="65px;" width="75px;">
                </a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-light" href="#", role="button" data-bs-toggle="dropdown">Universities</a>
                    <ul class="dropdown-menu">
                        {% for u in universities %}
                            <li><a class="dropdown-item" href="{% url 'dorm-detective:university' u.slug %}">{{ u.name }}</a></li>
                        {% endfor %}
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'dorm-detective:universities' %}">All Universities</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'dorm-detective:about' %}">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'dorm-detective:faq' %}">FAQs</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'dorm-detective:contact_us' %}">Contact Us</a>
                </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="navbar-brand text-light" href="{% url 'dorm-detective:my_account' user.id %}">
                        My Account
                        <img src="{% if user_profile.picture %}{{ user_profile.picture }}{% else %}{% static 'images/default_pp.png' %}{% endif %}" class="rounded" height="45px;" width="50px;" style="margin-left: 10px;">
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'dorm-detective:registration_register' %}">Register/Log In</a>
                </li>
            {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container-fluid content-container align-items-center">
    {% block content %}
    {% endblock %}
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
</body>
</html>

templates/dorm_detective_app/universities.html
{% extends 'dorm_detective_app/base.html' %}

{% block title_block %}
    Universities
{% endblock title_block %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'dorm-detective:index' %}">Home</a></li>
            <li class="breadcrumb-item active">Universities</li>
        </ol>
    </nav>

    <div class="row mb-3 text-center">
        <h2 class="mb-3 text-primary"><b>Universities</b></h2>
        <p><em>All Universities hosted by Dorm Detective are not endorsed. We do not receive from these Universities nor
            do we alter reviews.</em></p>
    </div>

    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for u in universities %}
            <div class="col">
                <a href="{% url 'dorm-detective:university' u.slug %}" style="text-decoration: none; color: black">
                    <div class="card h-100">
                        <img src="{% if u.picture %}{{ MEDIA_URL }}{{ u.picture }}{% else %}{{ STATIC_URL }}/images/uni_default.jpg{% endif %}" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title"><b>{{ u.name }}</b></h5>
                            <p class="card-text">{{ u.synopsis }}</p>
                        </div>
                        {% if accommodations %}
                        {% for a in accommodations %}
                            {% if a.university == u %}
                                <ul class="list-group list-group-flush">
                                    <div class="list-group-item">
                                        <a href="{% url 'dorm-detective:accommodation' u.slug a.slug %}">{{ a.name }}</a>
                                    </div>
                                </ul>
                            {% endif %}
                        {% endfor %}
                        {% endif %}
                        <div class="card-footer">
                            <a href="{{ u.website }}" target="_blank" class="card-link">University Website</a>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}